# -*- coding: utf-8 -*-
"""rashmika_pipeline (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4njMslmF41zMyt8tge4O71TiUOV1uKQ

**Objective**

To extract structured information from a healthcare provider participation agreement PDF using:

* OCR + image preprocessing

* LLM-based information extraction

* JSON → structured tables


**Scope of this POC:**

* Contract metadata

* Provider details

* Participation agreement

* Reimbursement rules

**Install System & Python Dependencies**
"""

!apt-get update
!apt-get install -y tesseract-ocr
!pip install pytesseract opencv-python pillow pymupdf

"""**Upload Contract PDF**"""

from google.colab import files

uploaded = files.upload()

"""**OCR + Image Preprocessing**

Improve image quality before OCR to increase text accuracy.
"""

import fitz  # PyMuPDF
import cv2
import pytesseract
import numpy as np
from PIL import Image

def preprocess_image(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Increase resolution
    gray = cv2.resize(gray, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)

    # Noise removal
    gray = cv2.GaussianBlur(gray, (5, 5), 0)

    # Adaptive thresholding
    thresh = cv2.adaptiveThreshold(
        gray,
        255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY,
        11,
        2
    )

    return thresh

def extract_text_from_pdf(pdf_path):
    doc = fitz.open(pdf_path)
    extracted_text = ""

    for page_number in range(len(doc)):
        page = doc.load_page(page_number)

        # Render PDF page as image
        pix = page.get_pixmap(dpi=300)
        img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

        # Convert to OpenCV format
        open_cv_img = np.array(img)
        open_cv_img = cv2.cvtColor(open_cv_img, cv2.COLOR_RGB2BGR)

        # Preprocess
        processed_img = preprocess_image(open_cv_img)

        # OCR
        text = pytesseract.image_to_string(
            processed_img,
            config="--oem 3 --psm 6"
        )

        extracted_text += f"\n--- PAGE {page_number + 1} ---\n{text}"

    return extracted_text

# Run OCR
pdf_file = "Request-to-Approve-Provider-Agreement-Exhibit-A-R031224.pdf"
ocr_text = extract_text_from_pdf(pdf_file)

# Save output
with open("ocr_output.txt", "w", encoding="utf-8") as f:
    f.write(ocr_text)

print("OCR completed. Output saved as ocr_output.txt")

files.download("ocr_output.txt")

"""**Load OCR text**"""

import pandas as pd

with open("ocr_output.txt", "r", encoding="utf-8") as f:
    ocr_text = f.read()

"""**Build Extraction Prompt**"""

prompt = f"""
You are given OCR-extracted text from a healthcare provider contract.

TASK:
1. Extract contract metadata
2. Extract provider details
3. Extract reimbursement rules ONLY
4. Extract Participation Agreement

Return output strictly in JSON with these keys:

contract_summary: {{
  contract_number,
  contract_type,
  state,
  effective_date,
  term
}}

provider_details: {{
  legal_name,
  dba_name,
  facility_type,
  provider_specialty,
  npi,
  tax_id
}}

participation_agreement_cover: {{
  agreement_type,
  icertis_contract_number,
  merlin_id,
  contract_creation_date,
  contract_contact_name,
  contract_contact_email,
  contractor_name,
  contractor_email
}}

reimbursement_rules: [
  {{
    plan_type,
    service_category,
    code_range,
    fee_schedule,
    reimbursement_percentage
  }}
]

TEXT:
{ocr_text}
"""

"""**Load OpenAI API Key**"""

from google.colab import userdata

api_key = userdata.get("OPENAI_API_KEY")

if not api_key:
    raise ValueError("OPENAI_API_KEY not found in Colab Secrets")

print("API key loaded successfully via Colab userdata")

"""**Call OpenAI LLM**"""

from openai import OpenAI

client = OpenAI(api_key=api_key)

response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {
            "role": "system",
            "content": "Return ONLY valid JSON. No markdown. No explanations."
        },
        {
            "role": "user",
            "content": prompt
        }
    ],
    temperature=0
)

structured_json = response.choices[0].message.content.strip()

print("Raw LLM response received")
print(structured_json[:700])

"""**Convert JSON → Structured Tables**"""

import json
import pandas as pd

data = json.loads(structured_json)

df_contract = pd.DataFrame([data["contract_summary"]])
df_provider = pd.DataFrame([data["provider_details"]])
df_reimbursement = pd.DataFrame(data["reimbursement_rules"])
df_participant = pd.DataFrame([data["participation_agreement_cover"]])

"""**Save Outputs**"""

df_contract.to_csv("contract_summary.csv", index=False)
df_provider.to_csv("provider_details.csv", index=False)
df_reimbursement.to_csv("reimbursement_rules.csv", index=False)
df_participant.to_csv("participation_agreement_cover.csv", index=False)

print("CSV files saved")

"""**Display table**"""

print("CONTRACT SUMMARY")
display(df_contract)

print("PROVIDER DETAILS")
display(df_provider)

print("PARTICIPATION AGREEMENT")
display(df_participant)

print("REIMBURSEMENT RULES")
display(df_reimbursement)